#travis


language: generic
sudo: required # we need superuser permissions
serices:
  - docker

before_install:
  - docker build -t akashmasand/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI = true akashmasand/reactapp npm run test -- --coverage