version: '3'

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # This is only for windows environment where windows does not detect changes with the app.

    build:
      context: . #basically where to look at while building the file
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"
    
    volumes: #This part basically sets up docker volumes. You can get rid of COPY . .
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #overrides the default npm command in the docker file